version: "3"

services:
  binance-trade-bot:
    build: .
    image: binance-trade-bot:dev
    volumes:
      - ./user.cfg:/app/user.cfg
      - ./data:/app/data
      - ./supported_coin_list:/app/supported_coin_list
      - ./config:/app/config
    command: python -m binance_trade_bot
    environment:
      - PYTHONUNBUFFERED=1

  # binance-trade-bot-api:
  #   build: .
  #   image: binance-bot:dev
  #   volumes:
  #     - ./user.cfg:/app/user.cfg
  #     - ./data:/app/data
  #     - ./supported_coin_list:/app/supported_coin_list
  #     - ./config:/app/config
  #   ports:
  #     - 5123:5123
  #   command: gunicorn binance_trade_bot.api_server:app -k eventlet -w 1 --threads 1 -b 0.0.0.0:5123
  #   depends_on:
  #     - binance-bot

  # sqlitebrowser:
  #   image: ghcr.io/linuxserver/sqlitebrowser
  #   container_name: sqlitebrowser
  #   environment:
  #     - PUID=1000
  #     - PGID=1000
  #     - TZ=Europe/Berlin
  #   volumes:
  #     - ./data/config:/config
  #     - ./data:/data
  #   ports:
  #     - 3000:3000
